### ISSUE TITLE
Improve save request validation

### ISSUE THREAD

**Issue by thefuxia** [wpsitecare/wp-featherlight#21] opened 2015-08-23 00:16 UTC
The current check on `save_post` is a little bit odd and incomplete:

The doc block for the method `\WP_Featherlight_Admin_Meta::stop_save()` says it return `void`. This makes the IDE complaining. :)

In `\WP_Featherlight_Admin_Meta::save_meta_boxes()` there is another check for the nonce. That belongs to the first method. There is at least no obvious reason to separate the checks.

There is no check for a switched multisite context: when a post is translated into another site of the network, `save_post` will be called on that other site again. This can lead to odd situations where data on other sites will be overwritten. See [my explanation on the MultilingualPress developer blog](http://make.marketpress.com/multilingualpress/2014/10/how-to-disable-broken-save_post-callbacks/).

Shouldn't there be a check for `current_user_can( 'edit_post', $post_id )`?

The checks in `\WP_Featherlight_Admin_Meta::stop_save()` should include all the tests mentioned above, each test should get its own `return false` for better readability (and cleaner commit messages).

Actually, I would move the request validation into a separate object, because that's a separate task. But for now, an improved check in the current class might be good enough.

**Comment by robneu** [comment] 2015-08-23 00:49
Thanks for the information about multisite and for catching the other two issues. I'll take a look at that post and clean that stuff up.

As for the nonce verification, the main reason that I have the nonce directly in the save method is because I'll get nagged by PHP_CodeSniffer for the raw `$_POST` variable being passed if I do something like this

``` php
...
    protected function validate_request( $data, $nonce, $action ) {
        if ( ! isset( $data[ $nonce ] ) || ! wp_verify_nonce( $data[ $nonce ], $action ) ) {
            return false;
        }
        return $data;
    }

    /**
     * Callback function for saving our testimonial details meta box data.
     * Handles data validation and sanitization for our content label.
     *
     * @since  0.1.0
     * @access public
     * @return void
     */
    public function save_meta_boxes( $post_id ) {
        // Bail if something is in progress.
        if ( $this->stop_save() ) {
            return;
        }

        if ( $data = $this->validate_request( $_POST, 'wp_featherlight_disable_nonce', 'toggle_wp_featherlight' ) ) {
            update_post_meta(
                $post_id,
                'wp_featherlight_disable',
                isset( $data['wp_featherlight_disable'] ) ? 'yes' : ''
            );
        }
    }
...
```

I'm not sure if there's a way around this or if the sniffs are set up that way by design to discourage that sort of abstraction.

**Comment by thefuxia** [comment] 2015-08-23 01:06
Well, you _have_ to access that variable at some point, so there is no way around it. The code sniffer is complaining about the current code too. You could pass `$_POST` into the class' constructor as `$user_data` to keep the class itself independent from a specific request type. This makes tests easier too, because you can then pass a custom array into the constructor.

Another notice: `save_meta_boxes()` should return a boolean value, so you can test that method.

**Comment by robneu** [comment] 2015-08-23 01:53
I'm sure this could be done more cleanly, but I think I've addressed all the issues at hand for now. I'll look into refactoring things into separate tasks more effectively for the next version.

Can you let me know if you see any major oversights or problem in those last two commits? If everything looks alright, I'll close this out and open a new issue for the code quality.

**Comment by thefuxia** [comment] 2015-08-23 02:21
I think your code was still too complex. :) See my pull request for a more simple attempt.

**Comment by robneu** [comment] 2015-08-23 03:07
I think this is all squared away now. Thanks for all the help!

**Closed as completed by robneu** 2015-08-23 03:07 UTC
